### PR TITLE
build(dist): Build output module using CommonJS

### PR DESCRIPTION
**Pull request by dottodot**
Output module needs to be in a form so that it can be used with Angular Universal using `node`. `node` currently do not support `es2015` `import` and `export` statements.

### CODE REVIEW

**Comment by NetanelBasal** [comment]
This will affect applications that do not use Angular Universal?

**Comment by dottodot** [comment]
As far as I know it shouldn't cause any issues it just changes how dependencies are required and makes it compatible with nodejs. 

With es2015 the output is
```
import { Subject } from "rxjs";
export function TakeUntilDestroy(constructor) {
    var originalDestroy = constructor.prototype.ngOnDestroy;
    constructor.prototype.componentDestroy = function () {
        this._takeUntilDestroy$ = this._takeUntilDestroy$ || new Subject();
        return this._takeUntilDestroy$.asObservable();
    };
    constructor.prototype.ngOnDestroy = function () {
        originalDestroy && typeof originalDestroy === 'function' && originalDestroy.apply(this, arguments);
        this._takeUntilDestroy$ && this._takeUntilDestroy$.complete();
    };
}
//# sourceMappingURL=angular2-take-until-destroy.js.map
```
and with commonjs it's
```
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
var rxjs_1 = require('rxjs');
function TakeUntilDestroy(constructor) {
  var originalDestroy = constructor.prototype.ngOnDestroy;
  constructor.prototype.componentDestroy = function() {
    this._takeUntilDestroy$ = this._takeUntilDestroy$ || new rxjs_1.Subject();
    return this._takeUntilDestroy$.asObservable();
  };
  constructor.prototype.ngOnDestroy = function() {
    originalDestroy &&
      typeof originalDestroy === 'function' &&
      originalDestroy.apply(this, arguments);
    this._takeUntilDestroy$ && this._takeUntilDestroy$.complete();
  };
}
exports.TakeUntilDestroy = TakeUntilDestroy;
//# sourceMappingURL=angular2-take-until-destroy.js.map

```

**Comment by NetanelBasal** [comment]
You can see [here](https://github.com/angular/angular/blob/master/packages/http/tsconfig-build.json#L8) that Angular also uses the `es2015` option.

**Comment by NetanelBasal** [comment]
Maybe we need to add - `"moduleResolution": "node"`?

**Comment by dottodot** [comment]
`"moduleResolution": "node"` is already there the problem is when es2015 is used to compile it will always declare dependencies as `import { Subject } from "rxjs";` and this type of import isn't currently supported in nodejs.

As yet I've not found any other way around this.

**Comment by NetanelBasal** [comment]
So I don't understand how the @angular packages are working when using Angular Universal? They are also using `es2015`.

**Comment by dottodot** [comment]
This might be of interest

https://github.com/angulartics/angulartics2/pull/139

Sounds like 2 different versions can be created to cover both. Not have chance to look into how to do it yet though.

**Comment by NetanelBasal** [comment]
I created a new package with support for `commonjs`. See if it helps. https://github.com/NetanelBasal/ngx-take-until-destroy

**Pull request closed without merging**
